build:
    environment:
        php: '5.6.0'
        php: '7.0.0'

    tests:
        override:
            -
                command: 'phpunit --coverage-clover=posprint-file'
                coverage:
                    file: 'posprint-file'
                    format: 'php-clover'

before_commands:
    - "composer install --prefer-source"

filter:
    excluded_paths: [tests/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage:
        enabled: false
        timeout: 600
        runs: 3
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
                - 'examples/*'
    
    # Code Coverage
    php_code_coverage:
        enabled: true
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
                - 'examples/*'

    # Code Sniffer            
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
            sniffs:
                generic:
                    files:
                        one_class_per_file_sniff: false
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
                - 'examples/*'

    # Copy/Paste Detector
    php_cpd:
        enabled: true
        excluded_dirs:
            - tests
            - vendor
            - examples

    # PHP CS Fixer (http://http://cs.sensiolabs.org/).
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
                - 'examples/*'

    # Analyzes the size and structure of a PHP project.
    php_loc:
        enabled: true
        excluded_dirs:
            - tests
            - vendor
            - examples

    # PHP Mess Detector (http://phpmd.org).
    php_mess_detector:
        enabled: true
        config:
            rulesets:
                - codesize
                - unusedcode
                - naming
                - design
            naming_rules:
                short_variable: { minimum: 3 }
        filter:
            excluded_paths:
                - 'test/*'
                - 'vendor/*'
                - 'examples/*'

    # Analyzes the size and structure of a PHP project.
    php_pdepend:
        enabled: true
        excluded_dirs:
            - tests
            - vendor
            - examples

    # Runs Scrutinizer's PHP Analyzer Tool
    # https://scrutinizer-ci.com/docs/tools/php/php-analyzer/config_reference
    php_analyzer:
        enabled: true
        config:
            checkstyle:
                enabled: true
                naming:
                    enabled: true
                    property_name: ^[_a-zA-Z][a-zA-Z0-9_]*$ #Allow underscores & caps
                    method_name: ^(?:[_a-zA-Z]|__)[a-zA-Z0-9_]*$ #Allow underscores & caps
                    parameter_name: ^[a-z][a-zA-Z0-9_]*$ # Allow underscores
                    local_variable: ^[a-zA-Z][a-zA-Z0-9_]*$ #Allow underscores & caps
                    exception_name: ^[a-zA-Z][a-zA-Z0-9]*Exception$
                    isser_method_name: ^(?:[_a-zA-Z]|__)[a-zA-Z0-9]*$ #Allow underscores & caps
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
                - 'examples/*'

    # Security Advisory Checker
    sensiolabs_security_checker: true                
